// A pass must always be able to name its sitting, including the first pass of
// one and including a sitting whose row never landed. The session id is
// therefore generated by the client before the insert leaves (2026-09-27).

import { renderHook, act, waitFor } from "@testing-library/react";

const mockInserts = [];
let mockInsertError = null;
jest.mock("../../supabaseClient", () => {
  function query(table) {
    let insertPayload = null;
    const api = {
      insert: (payload) => { insertPayload = payload; mockInserts.push({ table, payload }); return api; },
      select: () => api,
      eq: () => api,
      update: () => api,
      single: () => Promise.resolve({ data: null, error: null }),
      then: (resolve, reject) => Promise.resolve(
        insertPayload && table === "sam_sessions" && mockInsertError
          ? { data: null, error: mockInsertError }
          : { data: [], error: null }
      ).then(resolve, reject),
    };
    return api;
  }
  return {
    supabase: { from: (table) => query(table), auth: {
      getSession: async () => ({ data: { session: null } }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe() {} } } }),
    } },
    supabaseUrl: "http://localhost",
    supabaseAnonKey: "anon",
  };
});

const usePracticeSession = require("./usePracticeSession").default;
const { newSessionId } = require("./usePracticeSession");

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

beforeEach(() => {
  mockInserts.length = 0;
  mockInsertError = null;
  jest.spyOn(console, "log").mockImplementation(() => {});
  jest.spyOn(console, "error").mockImplementation(() => {});
  jest.spyOn(console, "warn").mockImplementation(() => {});
});
afterEach(() => jest.restoreAllMocks());

const sessionRow = () => mockInserts.find((i) => i.table === "sam_sessions")?.payload;

test("the id is known synchronously, before the insert resolves", () => {
  const { result } = renderHook(() => usePracticeSession());
  act(() => { result.current.startSession({ songId: "song-1", settings: { bpm: 60 } }); });
  // Not awaited: this is the window where a pass used to get session_id null.
  expect(result.current.getSessionId()).toMatch(UUID);
});

test("the row is inserted with that same id", async () => {
  const { result } = renderHook(() => usePracticeSession());
  await act(async () => { await result.current.startSession({ songId: "song-1", settings: {} }); });
  await waitFor(() => expect(sessionRow()).toBeTruthy());
  expect(sessionRow().id).toBe(result.current.getSessionId());
});

test("a failed insert detaches the sitting rather than leaving passes to fail a foreign key", async () => {
  mockInsertError = { code: "42501", message: "denied" };
  const { result } = renderHook(() => usePracticeSession());
  await act(async () => { await result.current.startSession({ songId: "song-1", settings: {} }); });
  await waitFor(() => expect(result.current.getSessionId()).toBeNull());
});

test("no song id: no row, no session", async () => {
  const { result } = renderHook(() => usePracticeSession());
  await act(async () => { await result.current.startSession({ songId: null, settings: {} }); });
  expect(sessionRow()).toBeUndefined();
  expect(result.current.getSessionId()).toBeNull();
});

test("ids are v4-shaped and distinct", () => {
  const ids = new Set(Array.from({ length: 50 }, () => newSessionId()));
  expect(ids.size).toBe(50);
  for (const id of ids) expect(id).toMatch(UUID);
});

// randomUUID is undefined outside a secure context, which is exactly how the
// phone reaches the dev server over plain http.
test("ids are still v4-shaped with no randomUUID, and with no crypto at all", () => {
  const getRandomValues = (a) => { for (let i = 0; i < a.length; i++) a[i] = i * 7; return a; };
  expect(newSessionId({ getRandomValues })).toMatch(UUID);
  expect(newSessionId(null)).toMatch(UUID);
});
