// A pass is never lost to a session row that never landed. The session id is
// generated by the client (usePracticeSession, 2026-09-27), so a pass can name a
// sitting whose insert failed; Postgres rejects that with 23503 and the pass is
// rewritten unattached.

import { renderHook, act, waitFor } from "@testing-library/react";

const mockInserts = [];
// (attemptNumber, row) => error | null
let mockRefuse = null;
jest.mock("../../supabaseClient", () => ({
  supabase: {
    from: (table) => ({
      insert: (row) => {
        mockInserts.push({ table, row });
        const error = mockRefuse ? mockRefuse(mockInserts.length, row) : null;
        return { then: (res, rej) => Promise.resolve({ error }).then(res, rej) };
      },
    }),
  },
}));

const useSamPasses = require("./useSamPasses").default;

beforeEach(() => {
  mockInserts.length = 0;
  mockRefuse = null;
  jest.spyOn(console, "log").mockImplementation(() => {});
  jest.spyOn(console, "error").mockImplementation(() => {});
});
afterEach(() => jest.restoreAllMocks());

function credit(result, extra) {
  act(() => result.current.armPass());
  act(() => {
    result.current.recordPass({
      songId: "song-1", snippet: null, sessionId: "sess-1", bpm: 60, playbackSpeed: 100,
      handMode: "both", playthrough: { hits: 4, misses: 0, notesPlayed: 4 }, ...extra,
    });
  });
}

const FK = { code: "23503", message: 'violates foreign key constraint "sam_passes_session_id_fkey"' };

test("a session foreign-key rejection rewrites the pass with no session", async () => {
  mockRefuse = (n) => (n === 1 ? FK : null);
  const onPassRecorded = jest.fn();
  const { result } = renderHook(() => useSamPasses({ onPassRecorded }));
  credit(result);
  await waitFor(() => expect(mockInserts).toHaveLength(2));
  expect(mockInserts[0].row.session_id).toBe("sess-1");
  expect(mockInserts[1].row.session_id).toBeNull();
  // Everything else about the pass is identical — only the sitting is dropped.
  expect(mockInserts[1].row).toMatchObject({ song_id: "song-1", hits: 4, notes_played: 4 });
  // The count only moves once, on the row that landed.
  await waitFor(() => expect(onPassRecorded).toHaveBeenCalledTimes(1));
});

test("the retry happens once: a second rejection is not retried again", async () => {
  mockRefuse = () => FK;
  const onPassRecorded = jest.fn();
  const { result } = renderHook(() => useSamPasses({ onPassRecorded }));
  credit(result);
  await waitFor(() => expect(mockInserts).toHaveLength(2));
  expect(mockInserts).toHaveLength(2);
  expect(onPassRecorded).not.toHaveBeenCalled();
});

test("any other error is not retried — a lost row must not become two attempts", async () => {
  mockRefuse = () => ({ code: "23514", message: "check constraint" });
  const { result } = renderHook(() => useSamPasses());
  credit(result);
  await waitFor(() => expect(mockInserts).toHaveLength(1));
  expect(mockInserts).toHaveLength(1);
});

test("a pass with no session is not retried when the foreign key complains", async () => {
  mockRefuse = () => FK;
  const { result } = renderHook(() => useSamPasses());
  credit(result, { sessionId: null });
  await waitFor(() => expect(mockInserts).toHaveLength(1));
  expect(mockInserts[0].row.session_id).toBeNull();
});
