-- 012 - a playlist may legitimately contain the same song twice
--
-- ============================================================================
-- WHY. THE BULK IMPORT'S DRY RUN FAILED ON FIVE REAL PLAYLISTS.
-- ============================================================================
-- Family party (5 duplicates), Awesome (3), 5K (4), Yoga (50) and Archived
-- Weezer (110) all hold the same video_id more than once. That is not a defect
-- in the data: a party mix repeats a song, and a discography compiled over years
-- accumulates the same track from several sources.
--
-- `dj_playlist_tracks_playlist_id_role_track_id_key` forbade it. That constraint
-- came from Block C and was correct FOR THE CASE IT WAS DESIGNED AGAINST -
-- CONCERT playlists, where a song twice in one zone is meaningless. Phase 6b
-- records the whole library, so the assumption stopped holding.
--
-- ⚠️ WHAT THE CONSTRAINT WAS ACTUALLY PROTECTING IS NOT WHAT IT SAYS. Spec §5
-- needs a track to be distinguishable BETWEEN zones - one row in cram and one in
-- body - so that "clear the cram list" is a delete of the cram rows that leaves
-- the concert order intact. That requires `role` IN THE KEY. It never required
-- uniqueness WITHIN a zone. The two were bundled into one constraint and only
-- the first half was load-bearing.
--
-- ============================================================================
-- POSITION BECOMES THE IDENTITY, AND IT ALREADY WAS
-- ============================================================================
-- `(playlist_id, role, position)` was already UNIQUE. Position is already the
-- ordering key, and already what set_video_id's reuse forced every caller to key
-- on - live data confirmed §5's warning that two playlists hold the SAME
-- set_video_id string for DIFFERENT songs. So this migration does not invent a
-- key; it stops enforcing a second one that no longer describes the data.
--
-- A slot still cannot be claimed twice. That is the invariant worth having.
--
-- ============================================================================
-- 🛑 DEFERRABLE HAS TO GO, AND THAT IS THE REAL COST OF THIS CHANGE
-- ============================================================================
-- POSTGRESQL WILL NOT ACCEPT A DEFERRABLE UNIQUE CONSTRAINT AS AN `ON CONFLICT`
-- ARBITER. record_dj_playlist upserts membership with
-- `onConflict: playlist_id,role,track_id`; once that constraint is gone the
-- upsert must arbitrate on position instead, and it cannot while position is
-- DEFERRABLE INITIALLY DEFERRED.
--
-- Why dropping deferrability is safe HERE, specifically:
--
--   * It existed so a WHOLESALE REORDER would not trip mid-statement - rows
--     swapping positions transiently collide while half are moved.
--   * With position as the arbiter that pattern disappears. The upsert
--     OVERWRITES SLOTS IN PLACE: the row at body position 3 becomes whatever
--     track is now at position 3. No row is ever moved to a different position,
--     so there is no transient state to defer past.
--   * record_dj_playlist is the ONLY writer of this table anywhere in the
--     system. Nothing performs individual position UPDATEs.
--
-- ⚠️ IF A MOVE-IN-PLACE WRITER IS EVER ADDED, THIS IS THE CONSTRAINT IT WILL
-- TRIP. It must either sort its updates to avoid transient collisions, or this
-- goes back to deferred and the upsert needs a different write strategy. Named
-- here so it is a decision then, not a surprise.
--
-- ============================================================================
-- CRAM STILL FORBIDS DUPLICATES - CONDITIONAL ON ZONE, NOT ON KIND
-- ============================================================================
-- A rule conditional on playlist KIND would be worse than the problem: it makes
-- correctness depend on a classification a human chose, and every caller would
-- have to know it. A rule conditional on ZONE is a different thing entirely -
-- the zones ALREADY mean different things (§5), the body is authored by Alex and
-- cram is generated by the system, and a duplicate cram row is always a bug: it
-- burns one of eight slots and shows the same song twice in a focus list.
--
-- So the protection is kept exactly where it still means something.

-- ---------------------------------------------------------------------------
-- 1. The duplicate ban goes.
-- ---------------------------------------------------------------------------
alter table public.dj_playlist_tracks
  drop constraint if exists dj_playlist_tracks_playlist_id_role_track_id_key;

-- ---------------------------------------------------------------------------
-- 2. Position becomes immediate, so it can arbitrate ON CONFLICT.
-- ---------------------------------------------------------------------------
alter table public.dj_playlist_tracks
  drop constraint if exists dj_playlist_tracks_playlist_id_role_position_key;

alter table public.dj_playlist_tracks
  add constraint dj_playlist_tracks_playlist_id_role_position_key
  unique (playlist_id, role, "position");

-- ---------------------------------------------------------------------------
-- 3. Cram keeps its uniqueness, via a partial index.
-- ---------------------------------------------------------------------------
create unique index if not exists dj_playlist_tracks_cram_track_uniq
  on public.dj_playlist_tracks (playlist_id, track_id)
  where role = 'cram';

comment on index public.dj_playlist_tracks_cram_track_uniq is
  'A song may appear many times in a playlist BODY - party mixes repeat, and a '
  'discography compiled over years accumulates the same track. It may never '
  'appear twice in CRAM: cram is generated by the system, holds about eight '
  'slots, and a duplicate there wastes one and shows the same song twice in a '
  'focus list. Conditional on ZONE, deliberately, and never on playlist kind - '
  'the zones already mean different things, whereas making correctness depend on '
  'a human''s classification of a playlist would put the rule somewhere no '
  'caller can see it.';

-- ---------------------------------------------------------------------------
-- 4. The table comment. It said something that is now FALSE.
-- ---------------------------------------------------------------------------
-- ⚠️ The old text - "A track may hold one row per zone" - was accurate and is
-- not any more. Leaving it would put a false statement in the authoritative
-- place, which is where a reader goes to settle exactly this question (§11.4).
comment on table public.dj_playlist_tracks is
  'DJ: playlist membership. A track may hold rows in BOTH zones - the same song '
  'in cram and in body is deliberate, and it is what makes "clear the cram list" '
  'a delete of the cram rows that leaves the concert order intact. '
  'Within the BODY a track may also appear MORE THAN ONCE: real playlists repeat '
  'songs, and forbidding it broke the Phase 6b import of five of them. '
  'Identity is (playlist_id, role, position) - a slot cannot be claimed twice, '
  'which is the invariant that matters. It is IMMEDIATE rather than deferrable '
  'because record_dj_playlist arbitrates ON CONFLICT against it, and PostgreSQL '
  'will not accept a deferrable constraint as an arbiter; the upsert overwrites '
  'slots in place and never moves a row, so nothing needs deferring. '
  'CRAM still forbids duplicates - see dj_playlist_tracks_cram_track_uniq.';

-- ---------------------------------------------------------------------------
-- VERIFY
-- ---------------------------------------------------------------------------
-- ⚠️ THE ARBITER TEST IS THE POINT OF THIS BLOCK, AND IT MUST BE A REAL UPSERT.
-- Asserting that pg_constraint holds a non-deferrable row proves the SHAPE of
-- the constraint and says nothing about whether PostgreSQL will ACCEPT it as an
-- ON CONFLICT arbiter - which is the entire reason for change 2. A check that
-- reads the catalogue instead of exercising the behaviour is the same mistake as
-- proving a module parses and reporting that it imports (§11.18).
--
-- ⚠️ The probe writes and deletes real rows, so the audit log keeps a trace of a
-- membership row at position 999999 appearing and vanishing. That is the correct
-- trade: suppressing the trigger would mean a migration writing to an audited
-- table without being audited.
do $$
declare
  pid uuid;
  tid uuid;
  dupes_ok  boolean := false;
  arbiter_ok boolean := false;
  cram_ok   boolean := false;
  n int;
  why text;
begin
  select p.id into pid from public.dj_playlists p limit 1;
  select t.id into tid from public.dj_tracks t limit 1;
  if pid is null or tid is null then
    raise exception 'cannot verify 012: need at least one dj_playlists and one '
      'dj_tracks row to exercise the constraints. Do NOT mark this migration '
      'done on an empty database - the checks below would all pass vacuously.';
  end if;

  -- (a) The same track twice in the BODY, at different positions. This is the
  --     case that failed for five playlists.
  begin
    insert into public.dj_playlist_tracks (playlist_id, track_id, role, "position")
    values (pid, tid, 'body', 999998), (pid, tid, 'body', 999999);
    dupes_ok := true;
  exception when others then why := sqlerrm;
  end;

  -- (b) THE ARBITER. A real ON CONFLICT upsert against the position constraint.
  --     If PostgreSQL refuses it as an arbiter this raises
  --     "there is no unique or exclusion constraint matching the ON CONFLICT
  --     specification" - which is precisely the failure this migration exists to
  --     prevent, discovered here rather than in the importer.
  if dupes_ok then
    begin
      insert into public.dj_playlist_tracks
        (playlist_id, track_id, role, "position", added_reason)
      values (pid, tid, 'body', 999999, 'import')
      on conflict (playlist_id, role, "position")
      do update set added_reason = excluded.added_reason;
      arbiter_ok := true;
    exception when others then why := sqlerrm;
    end;
  end if;

  -- (c) The negative control: cram must STILL refuse a duplicate. Dropping one
  --     unique constraint and adding a partial one is exactly where the partial
  --     predicate ends up wrong and nothing ever complains again.
  begin
    insert into public.dj_playlist_tracks (playlist_id, track_id, role, "position")
    values (pid, tid, 'cram', 999998), (pid, tid, 'cram', 999999);
  exception
    when unique_violation then cram_ok := true;
    when others then null;
  end;

  delete from public.dj_playlist_tracks
   where playlist_id = pid and "position" in (999998, 999999);

  if not dupes_ok then
    raise exception 'the same track twice in one body was still REFUSED (%). '
      'The import this migration unblocks would still fail.', coalesce(why, '?');
  end if;
  if not arbiter_ok then
    raise exception 'ON CONFLICT (playlist_id, role, position) was REJECTED (%). '
      'PostgreSQL will not use this constraint as an arbiter, so '
      'record_dj_playlist cannot upsert membership. DO NOT DEPLOY THE HANDLER '
      'CHANGE.', coalesce(why, '?');
  end if;
  if not cram_ok then
    raise exception 'cram accepted a DUPLICATE track. '
      'dj_playlist_tracks_cram_track_uniq is not enforcing anything.';
  end if;

  select count(*) into n from public.dj_playlist_tracks
   where "position" in (999998, 999999);
  if n <> 0 then
    raise exception 'the verification left % probe row(s) behind.', n;
  end if;

  if exists (select 1 from platform.conformance_failures) then
    raise exception 'platform.conformance_failures is not empty after this '
      'migration. Run: select * from platform.conformance_failures;';
  end if;

  raise notice '012 verified: body duplicates allowed, ON CONFLICT (playlist_id, '
    'role, position) accepted as an arbiter, cram duplicates still refused.';
end $$;

-- Belt and braces, from a tool call rather than SQL:
--   check_platform_conformance   ->  must report CONFORMANT (28 tables)
--
-- ⚠️ THEN DEPLOY THE HANDLER, OR THE IMPORT STILL FAILS:
--   record_dj_playlist  - onConflict becomes playlist_id,role,position
--                       - the duplicate (role, video_id) validation is removed
--   npx supabase functions deploy mcp --no-verify-jwt
