-- Purpose: Read-only diagnostic: how many sam_passes rows carry no session_id, when they were written, and how many in-session streaks the gap could have broken.
-- Kind: diagnostic / verification query (nothing is applied, nothing changes)
-- Applied: N/A — this file is a SELECT. Run it whenever the question comes up.
--
-- All SQL lives in supabase/migrations/ (see .claude/CLAUDE.md). Numbering is
-- the order files were ADDED here. Alex runs every file himself.

-- ============================================================================
-- Which existing passes cannot name their sitting
-- Warm-up ladder Milestone 2, part 1
-- supabase/migrations/079_sam_passes_null_session_diagnostic.sql
--
-- WHY THIS EXISTS. sam_plan_item_progress.longest_qualifying_streak counts a
-- streak WITHIN ONE SESSION, and a pass whose session_id is null cannot be
-- attributed to a sitting, so migration 078 treats each one as a session of its
-- own. That under-counts a streak rather than inventing one, but it under-counts
-- it silently, so it matters how many such rows there are and whether they are
-- still being made.
--
-- The app-side cause was fixed on 2026-09-27: the session id is now generated by
-- the client before the session row is inserted, so a pass can always name its
-- sitting (src/sam/lib/usePracticeSession.js, `newSessionId`). Rows written
-- BEFORE that fix keep their nulls — they are history, and history is not
-- rewritten. This query says how much history is affected.
--
-- NOTHING HERE IS A BACKFILL, and a backfill is not proposed: attributing an old
-- pass to a sitting by time proximity would be a guess, and a guess in this
-- column would silently merge two sittings into one streak. A null that means
-- "not known" is the honest value.
-- ============================================================================

select json_build_object(

  -- The headline: how many passes carry no sitting, overall and among the rows
  -- that could ever matter to a streak (a pass with no notes is not an attempt).
  'totals', (select json_agg(t) from (
     select count(*)                                                        as passes,
            count(*) filter (where session_id is null)                      as no_session,
            count(*) filter (where session_id is null and notes_played > 0) as no_session_and_measured,
            min(completed_at) filter (where session_id is null)             as earliest_null,
            max(completed_at) filter (where session_id is null)             as latest_null
       from sam_passes
  ) t),

  -- Is it still happening? Anything dated on or after the fix went live is the
  -- number to watch: it should stay at whatever it is the day the app deploys
  -- and never grow after that.
  'by_pacific_day_last_30', (select json_agg(t) from (
     select (completed_at at time zone 'America/Los_Angeles')::date as pt_day,
            count(*)                                   as passes,
            count(*) filter (where session_id is null) as no_session
       from sam_passes
      where completed_at >= now() - interval '30 days'
      group by 1
      order by 1 desc
  ) t),

  -- WAS IT THE INSERT WINDOW OR A DEAD SESSION? A pass written in the window
  -- where the session row was still being inserted is the FIRST pass of its
  -- sitting and is followed, seconds later, by passes that DO name a session on
  -- the same song. A sitting whose insert failed outright has no such neighbour.
  -- Two very different stories, and the fix closes both.
  'null_passes_with_a_sitting_alongside', (select json_agg(t) from (
     select pa.id,
            pa.completed_at,
            pa.song_id,
            pa.snippet_id,
            (select min(nb.session_id::text)
               from sam_passes nb
              where nb.song_id = pa.song_id
                and nb.snippet_id is not distinct from pa.snippet_id
                and nb.session_id is not null
                and nb.completed_at > pa.completed_at
                and nb.completed_at < pa.completed_at + interval '5 minutes'
            ) as next_session_within_5_min
       from sam_passes pa
      where pa.session_id is null
        and pa.notes_played > 0
      order by pa.completed_at desc
      limit 50
  ) t),

  -- The cost, stated as the streak arithmetic. For each Pacific day and range,
  -- how many measured passes had no sitting: that is how many one-pass "sessions"
  -- migration 078 has to invent, and so how many places a real streak was split.
  'days_where_a_streak_could_have_been_split', (select json_agg(t) from (
     select (completed_at at time zone 'America/Los_Angeles')::date as pt_day,
            song_id,
            snippet_id,
            count(*) filter (where session_id is null) as measured_passes_with_no_sitting,
            count(*)                                   as measured_passes
       from sam_passes
      where notes_played > 0
      group by 1, 2, 3
     having count(*) filter (where session_id is null) > 0
      order by 1 desc, 4 desc
      limit 50
  ) t),

  -- Sessions that were deleted would also null a pass out (ON DELETE SET NULL on
  -- sam_passes.session_id), so this separates "never knew" from "knew and lost
  -- it". A non-zero count here is not something the app fix can prevent.
  'sessions_table_shape', (select json_agg(t) from (
     select (select count(*) from sam_sessions)                        as sessions,
            (select count(*) from sam_sessions where ended_at is null) as never_closed
  ) t)

) as result;
